### PR TITLE
resume failed revisions

### LINKED ISSUE #14: Wiederaufnahme einer fehlgeschlagenen Synchronisation.
Wenn aktuell eine Synchronisation fehlschlägt, beginnt sie beim nächsten Lauf wieder von vorne. Dies kann bei sehr grossen Synchronisations-Jobs mit mehreren tausend Datensätzen, dazu führen, dass die Synchronisation jedesmal Fehlschlägt (Verbindungsfehler) und somit nicht mehr weiter kommt.

**Lösungsansatz**
Den Synchronisationsfortschritt tracken (zB in der zum Prozess gehörenden Revision) und bei Neustart des Prozesses die bereits Synchronisierten Datensätze überspringen (analog dem `--offset` CLI-Argument).

### LINKED ISSUE #15: Log Einträge mit mit Job-Config präfixen
Mittlerweilen haben wir verschiedene Mailchimp instanzen, die synchronisiert werden. Jede Instanz hat ihr eigenes Config.yml. In den Fehlerlogs steht zur Zeit nicht, bei der Synchronisation welcher Instanz der Fehler aufgetreten ist. --> Alle Log-Einträge zB mit dem entsprechenden Config-File-Name präfixen.

### LINKED ISSUE #17: Angabe Config in Mailchimp Webling Sync Error
Wenn Datensätze direkt im Mailchimp eingefügt werden, statt über Webling, löst dies eine Mail an die im config gesetzte Emailadresse aus. Es wäre hilfreicht, wenn in der Mail stehen würde, welche Mailchimpinstanz es betrifft (resp. welches config-file), da es Personen gibt, die für mehrere Instanzen verantwortlich sind.

### PR DESCRIPTION
**Pull request by cyrillbolliger**
* closes #14
* closes #15
* closes #17

### CODE REVIEW

**Review by sandrotanner — APPROVED** [review]
Looks good. TIL about ReflectionClasses

**Review by sandrotanner — CHANGES_REQUESTED** [review]
Still some tests failing but now at least travis "works" ¯\\_(ツ)_/¯

**Comment by cyrillbolliger** [comment]
:100: I'll have a closer look tomorrow.

**Review by cyrillbolliger — COMMENTED** [review]
Great, 1000 thanks for this excellent commits!

Next steps:
* upgrade to php8
* remove legacy code from xdebug 2.x

**Review by sandrotanner — APPROVED** [review]

**Pull request merged**
